export const BTN_TXT = {
	FORGET_PASSWORD: 'I forgot my password',
	UPDATE_PASSWORD: 'Update password',
	SIGN_IN: 'Sign in',
	ADD_NEW_CLIENTS: 'Add New Client',
	EDIT_CLIENT: 'Edit Client',
	EDIT_INFO: 'Edit Info',
	CANCEL: 'Cancel',
	UPLOAD_NEW_PICTURE: 'Upload New Picture',
	UPLOAD_LOAN_FILES: 'Upload Loan Files',
	SEND_MESSAGE: 'Send Message',
	SEND_EMAIL: 'Send Email',
	FINISH_SIGN_UP: 'Finish Sign Up',
	ADD_NEW_BRANCH: 'Add New Branch',
	EDIT_BRANCH: 'Edit Branch',
	ADD_NEW_ROLE: 'Add New Role',
	YES_SURE: 'Yes, I’m sure.',
	GO_BACK: 'Go Back',
	CREATE_BRANCH: 'Create Branch',
	CREATE_ROLE: 'Create Role',
	EDIT_ROLE: 'Edit Role',
	VIEW: 'View',
	CREATE_STAFF: 'Create Staff',
	CREATE_FEE_TYPE: 'Create Fee Type',
	EDIT_STAFF: 'Edit Staff',
	UPLOAD_FILES: 'Upload Files',
	ADD_STAFF: 'Add Staff',
	ADD_LOAN_PRODUCT: 'Add Loan Product',
	ADD_FEE_TYPE: 'Add New Fee Type',
	ADJUST_ROLE_PERMISSIONS: 'Adjust Role Permissions',
	SAVE_ADJUSTMENTS: 'Save Adjustments',
	EDIT_FEE_TYPE: 'Edit Fee Type',
	CREATE_LOAN_PRODUCT: 'Create Loan Product',
	EDIT_LOAN_PRODUCT: 'Edit Loan Product',
	ADD_SAVINGS_PRODUCT: 'Add Savings Product',
	CREATE_SAVINGS_PRODUCTS: 'Create Savings Product',
	CONFIRM: 'Confirm',
	SAVE_CHANGES: 'Save Changes',
	DEACTIVATE_CLIENT: 'Deactivate Client',
	REACTIVATE_CLIENT: 'Reactivate Client',
	CREATE_CLIENT: 'Create Client',
};

export const PLACEHOLDERS = {
	SEARCH: 'Search...',
	SEARCH_CLIENTS: 'Search Clients...',
	SEARCH_ACCOUNTS: 'Search Accounts...',
	SEARCH_LOANS: 'Search Loans...',
	TYPE_MESSAGE: 'Type message here...',
	TYPE_DAYS: 'Type days here...',
	TYPE_CLIENTS: 'Type Client’s name here...',
	TYPE_PASSWORD: 'Type new password here...',
	REPEAT_PASSWORD: 'Repeat new password here...',
	SEARCH_BANKS: 'Search banks and branches...',
	TYPE_NAME: 'Type name here...',
	SELECT_BRANCH: 'Select Branch',
	SEARCH_LOAN_SETTINGS: 'Search loans settings...',
	NOTES_HERE: 'Notes appear here.',
	TYPE_TITLE: 'Type title here...',
	TYPE_NIN: 'Type NIN# here...',
	TYPE_PAY: 'Type pay here...',
	TYPE_COMMISSION: 'Type commission % here...',
	JONATHAN: 'Jonathan',
	AKELLO: 'Akello',
	MALE: 'Male',
	PRIMARY_CELL_PHONE_EXAMPLE: '888-888-8888',
	DASH: '-',
	EMAIL_EXAMPLE: 'j.akello@gmailcom',
	NIN_EXAMPLE: '1234567890',
	DATE_OF_BIRTH_EXAMPLE: '2/27/1964',
	XXX_XXX_XXXX: ' XXX-XXX-XXXX',
	ADDRESS_LINE_1_EXAMPLE: '12345 Main Street',
	ADDRESS_LINE_2_EXAMPLE: 'Apt 123',
	KAMPALA: 'Kampala',
	UGANDA: 'Uganda',
	SEARCH_FEES: 'Search Fees...',
	TYPE_RATE: 'Type rate here...',
	SELECT_ROLE: 'Select role',
	TYPE_AMOUNT: 'Type fixed amount here...',
	SELECT_FEE: 'Select Fee',
	SEARCH_PRODUCT: 'Search Product...',
	TYPE_CASH: 'Type cash here...',
	SAMPLE_BUSINESS_TYPE: 'Sample Business Type',
};

export const LABELS = {
	EMAIL: 'Email',
	PASSWORD: 'Password',
	CURRENT_PASSWORD: 'Current Password',
	CREATE_NEW_PASSWORD: 'Create your new password',
	NEW_PASSWORD: 'New Password',
	REPEAT_NEW_PASSWORD: 'Repeat new Password',
	GENERAL_INFORMATION: 'General Information',
	BUSINESS_INFORMATION: 'Business Information',
	FAMILY_INFORMATION: 'Family Information',
	SAVING_INFORMATION: 'Saving Information',
	PAY_INFORMATION: 'Pay Information',
	POSITION_AND_PERMITIONS: 'Position and Permissions',
	NEXT_OF_KIN_INFO: 'Next-of-Kin Information',
	NEXT_OF_KIN_NAME: 'Next-of-Kin Name',
	NEXT_OF_KIN_CELL: 'Next-of-Kin Cell',
	NEXT_OF_KIN_NIN: 'Next-of-Kin NIN #',
	POSITION: 'Position',
	ROLE: 'Role',
	BASE_PAY: 'Base Pay',
	COMISSION: 'Commission %',
	FIRST_NAME: 'First Name',
	GENDER: 'Gender',
	ADDRESS_LINE: 'Address Line',
	CITY: 'City',
	COUNTRY: 'Country',
	VILLAGE: 'Village',
	PARISH: 'Parish',
	SUBCOUNTRY: 'Subcountry',
	DISTRICT: 'District',
	LAST_NAME: 'Last Name',
	PRIMARY_CELL_PHONE: 'Primary Cell Phone',
	SECONDARY_CELL_PHONE: 'Secondary Cell Phone',
	EMAIL_ADDRESS: 'Email Address',
	NIN: 'NIN #',
	DATE_OF_BIRTH: 'Date of Birth',
	BUSINESS_NAME: 'Business Name',
	BUSINESS_REGISTRATION: 'Business Registration #',
	BUSINESS_TYPE: 'Business Type',
	SPOUSE_NAME: 'Spouse Name',
	SPOUSE_CELL: 'Spouse Cell',
	SPOUSE_NIN: 'Spouse NIN #',
	SAVINGS_AMOUNT: 'Savings Amount',
	NOTES: 'Notes',
	NOTES_HERE: 'Notes appear here.',
	FILES: 'Files',
	LOAN_TYPE: 'Loan Type',
	CLIENT: 'Client',
	LOAN_PURPOSE: 'Loan Purpose',
	LOAN_NUMBER: 'Loan Number',
	DISPURSEMENT_METHOD: 'Dispursement Method',
	LOAN_AMOUNT: 'Loan Amount $',
	DISPURSEMENT_DATE: 'Dispursement Date',
	INTEREST_METHOD: 'Interest Method',
	INTEREST_RATE: 'Interest Rate',
	REPAYMENT_CYCLE: 'Repayment Cycle',
	DURATION: 'Duration',
	NUMBER_OF_REPAYMENT: 'Number of Repayments',
	FEES: 'Fees',
	GUARANTOR: 'Guarantor',
	LOAN_FILES: 'Loan Files',
	EMPTY_LABEL: '⠀⠀⠀⠀',
	LOAN_STATUS: 'Load Status',
	LOAN_TERMS: 'Loan Terms',
	LOAN_BALANCES: 'Loan Balances',
	ADD_NEW_LOAN: 'Add New Loan',
	EDIT_LOAN: 'Edit Loan',
	EDIT_SAVING_PRODUCT: 'Edit Saving Product',
	ARE_YOU_SURE: 'Are you sure?',
	BANK_NAME: 'Associated Bank Name',
	PERMISSIONS: 'Permissions',
	POSITION_TITLE: 'Position Title',
	ADD_STAFF_MEMBER: 'Add New Staff Member',
	EDIT_STAFF_MEMBER: 'Edit Staff Member',
	LOAN_FEE_NAME: 'Loan Fee Name',
	FEE_INTEREST_RATE: 'Fee Interest Rate',
	LOAN_OFFICER_PERMISSIONS: 'Loan Officer Permissions',
	USER_OFFICER_PERMISSIONS: 'User Officer Permissions',
	FEE_FIXED_AMOUNT: 'Fee Fixed Amount',
	LOAN_PRODUCT_NAME: 'Loan Product Name',
	FREQUENCY: 'Frequency',
	PENALTY_INFORMATION: 'Penalty Information',
	LATE_PAYMENT_PENALTY: 'Late Payment Penalty',
	ENABLE_LATE_PAYMENT_PENALTY: 'Enable Late Payment Penalty',
	NUMBER_OF_GRACE_PERIOD_DAYS: 'Number of Grace Period Days',
	PENALTY_INTEREST_RATE: 'Penalty Interest Rate',
	PENALTY_FIXED_AMOUNT: 'Penalty Fixed Amount',
	POST_MATURITY_DATE_PENALTY: 'Post Maturity Date Penalty',
	ENABLE_POST_MATURITY_DATE_PENALTY: 'Enable Post Maturity Date Penalty',
	LOAN_FEES: 'Loan Fees',
	SAVINGS_PRODUCT_NAME: 'Savings Product Name',
	ADD_SAVINGS_PRODUCT: 'Add Savings Product',
	ANNUAL_INTEREST_RATE: 'Annual Interest Rate %',
	WHEN_SHOULD_INTEREST_BE_ADDED: 'When should Interest be added to account',
	INTEREST_POSTING_FREQUENCY: 'Interest Posting Frequency',
	MINIMUM_BALANCE_FOR_WITHDRAWAL: 'Minimum Balance for Withdrawal',
	FEE_AMOUNT: 'Fee Amount',
	CASH: 'Cash',
	SAVINGS_INTEREST: 'Savings Interest',
};

export const VALIDATION_MESSAGES = {
	REQUIRED: 'Required field.',
	PASSWORD_REQUIREMENTS: 'Password should be of min 8 digits with at least 1 upper 1 lower case and 1 special symbol.',
	MATCH_PASSWORDS: 'Passwords do not match.',
	EMAIL_FIELD: 'Please use correct email',
};

export const MESSAGES = {
	HELLO_MESSAGE: name => `Hello, ${name}! Welcome to Zimba.`,
	MESSAGE: 'Message',
	LINK_HAS_BEEN_SEND_TO_YOUR_EMAIL: 'Link has been send to your email',
	PASSWORD_SUCCESSFULLY_UPDATED: 'Password successfully updated',
	BRANCH_SUCCESSFULLY_CREATED: 'Branch successfully created',
	ROLE_SUCCESSFULLY_CREATED: 'Role successfully created',
	LOAN_SUCCESSFULLY_CREATED: 'Loan successfully created',
	CLIENT_SUCCESSFULLY_CREATED: 'Client successfully created',
	SAVING_PRODUCT_SUCCESSFULLY_CREATED: 'Saving product successfully created',
	FEE_SUCCESSFULLY_CREATED: 'Fee successfully created',
	BRANCH_SUCCESSFULLY_UPDATED: 'Branch successfully updated',
	ROLE_SUCCESSFULLY_UPDATED: 'Role successfully updated',
	SAVING_PRODUCT_SUCCESSFULLY_UPDATED: 'Saving product successfully updated',
	CLIENT_SUCCESSFULLY_UPDATED: 'Client successfully updated',
	FEE_SUCCESSFULLY_UPDATED: 'Fee successfully updated',
	LOAN_SUCCESSFULLY_UPDATED: 'Loan successfully updated',
	STAFF_MEMBER_SUCCESSFULLY_UPDATED: 'Staff member successfully updated',
	ARE_YOU_SURE_TO_REACTIVATE:
		'Are you sure you want to reactivate this branch? Doing so will cause all users of this branch to regain access to Zimba. You can deactivate it again at any time.',
	ARE_YOU_SURE_TO_DEACTIVATE:
		'Are you sure you want to deactivate this branch? Doing so will cause all users of this branch to lose access to Zimba. If you want to restore access, you will have to reactivate this branch. ',
	ARE_YOU_SURE_TO_REACTIVATE_CLIENTS: 'Are you sure you want to reactivate this client?',
	ARE_YOU_SURE_TO_DEACTIVATE_CLIENTS: 'Are you sure you want to deactivate this client?',
	ARE_YOU_SURE_TO_REACTIVATE_SAVING: 'Are you sure you want to reactivate this savings product?',
	ARE_YOU_SURE_TO_DEACTIVATE_SAVING: 'Are you sure you want to deactivate this savings product?',
	ARE_YOU_SURE_TO_REACTIVATE_LOAN_PRODUCT: 'Are you sure you want to reactivate this loan product?',
	ARE_YOU_SURE_TO_DEACTIVATE_LOAN_PRODUCT: 'Are you sure you want to deactivate this loan product?',

	ARE_YOU_SURE_TO_REACTIVATE_FEE: 'Are you sure you want to reactivate this fee?',
	ARE_YOU_SURE_TO_DEACTIVATE_FEE: 'Are you sure you want to deactivate this fee?',

	ARE_YOU_SURE_TO_REACTIVATE_STAFF:
		'Are you sure you want to reactivate this assignment? Doing so will cause the user to regain access to Zimba. You can deactivate it again at any time.',
	ARE_YOU_SURE_TO_DEACTIVATE_STAFF:
		'Are you sure you want to deactivate this assignment? Doing so will cause the user to lose access to Zimba. If you want to restore access, you will have to reactivate this assignment.',

	ARE_YOU_SURE_TO_REACTIVATE_ROLES: 'Are you sure you want to reactivate this role?',
	ARE_YOU_SURE_TO_DEACTIVATE_ROLES: 'Are you sure you want to deactivate this role?',
};

export const TXT = {
	YES: 'Yes',
	NO: 'No',
	HOME: 'Home',
	CLIENTS: 'Clients',
	VIEW_CLIENTS: 'View Clients',
	SEND_SMS_TO_CLIENT: 'Send SMS to a Client',
	SEND_SMS_TO_CLIENTS: 'Send SMS to Clients',
	SAVINGS: 'Savings',
	VIES_SAVINGS_ACCOUNTS: 'View Savings Accounts',
	SAVINGS_DEPOSITS_WITHDRAWALS: 'Savings Deposits + Withdrawals',
	KAMPALA_BRANCH: 'Kampala Branch',
	TOTAL_CLIENTS: 'Total Clients',
	FINISH_SIGN_UP_WITH: 'Finish Signing Up with Zimba',
	CONFIRM_INFO: 'Please confirm your Information Below',
	MY_PROFILE: 'My Profile',
	VIEW_MY_PROFILE: 'View My Profile',
	CHANGE_PASSWORD: 'Change Password',
	LOG_OUT: 'Log Out',
	INDIVIDUAL: 'Individual',
	GROUP: 'Group',
	RECIPIENT: 'Recipient',
	GROUP_CATEGORY: 'Group Category',
	LOANS: 'Loans',
	VIEW_LOANS: 'View Loans',
	DUE_LOANS: 'Due Loans',
	LOANS_IN_ARREARS: 'Loans in Arrears',
	NO_REPAYMENTS: 'No Repayments',
	PAST_MATURITY_DATE: 'Past Maturity Date',
	LOAN_CALCULATOR: 'Loan Calculator',
	ADD_GUARANTORS: 'Add Guarantors',
	LOAN_APPROVAL: 'Loan Approval',
	LOAN_CASH_PAYMENT: 'Loan Cash Payment',
	REPORTS: 'Reports',
	MONTHLY_REPORT: 'Monthly Report',
	LOAN_REPORT: 'Loan Report',
	SHARES: 'Shares',
	VIEW_SHAREHOLDERS: 'View Shareholders',
	BUY_SHARES: 'Buy Shares',
	SELL_SHARES: 'Sell Shares',
	OTHER_INCOME: 'Other Income',
	EXPENSES: 'Expenses',
	ACCOUNTING: 'Accounting',
	MONTHLY_CASHFLOW: 'Monthly Cashflow',
	PROFILE_LOSS_STATEM: 'Profit/Loss Statem',
	BALANCE_SHEETS: 'Balance Sheets',
	ADMIN: 'Admin',
	LOANS_SETTINGS: 'Loans Settings',
	FEE_SETTINGS: 'Fee Settings',
	SAVINGS_SETTINGS: 'Savings Settings',
	STAFF: 'Staff',
	ROLES_AND_PERMISSIONS: 'Roles and Permissions',
	MASTER_LEDGER: 'Master Ledger',
	PROVIDE_EMAIL_FOR_RESET_PASSWORD: 'Please, Provide email for reset password',
	PROVIDE_NEW_PASSWORD: 'Please, Provide new password',
	REVIEW_INFO_BELOW: 'Review your information below. If any info is incorrect, please contact your administrator',
	BANKS_AND_BRANCHES: 'Banks and Branches',
	ROLE_DESCRIPTION: 'Role Description',
	ADD_CLIENTS: 'Add Clients',
	VIEW_SAVINGS: 'View Savings',
	ADD_SAVINGS: 'Add Savings',
	ADD_LOANS: 'Add Loans',
	POST_MATURITY_DATE_LOANS: 'Post Maturity Date Loans',
	NEED_ASSISTANCE: 'Need assistance? Go to our ',
	PERMISSIONS: 'Permissions',
	PLEASE_NOTE_ADJUSTMENTS:
		'PLEASE NOTE: Adjustments will ONLY be applied to this specific user. To change the permissions for an entire role category, go to the Roles and Permssions screen.',
	FIXED_AMOUNT: 'Fixed Amount',
	INTEREST_RATE: 'Interest rate',
	DAILY: 'Daily',
	WEEKLY: 'Weekly',
	MONTHLY: 'Monthly',
	QUARTERLY: 'Quarterly',
	ANNUALLY: 'Annually',
	FLAT: 'Flat',
	DECLINING_BALANCE: 'Declining Balance',
	FIXED_CASH_WITHDRAWAL: 'Fixed Cash Withdrawal',
	CASH_WITHDRAWAL: 'Cash Withdrawal',
	CLIENT_DETAILS: 'Client Details',
	EDIT_CLIENT: 'Edit Client',
	ADD_NEW_CLIENT: 'Add New Client',
};

export const TABLE = {
	UNIQUE: 'Unique #',
	EMAIL: 'Email',
	MOBILE: 'Mobile',
	FIRST_NAME: 'First Name',
	SURNAME: 'Surname',
	ACCOUNT: 'Account #',
	SAVING_PRODUCT: 'Saving Product',
	SAVING_BALANCE: 'Saving Balance',
	LAST_TRANSACTION: 'Last Transaction',
	PRINCIPLE: 'Principle',
	INTEREST: 'Interest',
	LATE_FEES: 'Late Fees',
	TOTALS: 'Totals',
	BRANCH_NAME: 'Branch Name',
	IDENTIFICATION_NUMBER: 'Identification Number',
	ASSOCIATED_BANK: 'Associated Bank',
	USERS: 'Users',
	ROLE_NAME: 'Role Name',
	SET_PERMISSIONS: 'Set Permissions',
	BRANCH: 'Branch',
	NAME: 'Name',
	POSITION: 'Position',
	ROLE: 'Role',
	SALARY: 'Salary',
	DURATION_WITH_COMPANY: 'Duration with Company (Months)',
	STATUS: 'Status',
	BRANCH_ACCESS: 'Branch Access',
	PRODUCT_NAME: 'Product Name',
	PENALTY: 'Penalty',
	FEES: 'Fees',
	FEE_NAME: 'Fee Name',
	FEE_TYPE: 'Fee Type',
	RATE_AMOUNT: 'Rate/Amount',
	ACTIONS: 'Actions',
	ANNUAL_INTEREST_RATE: 'Annual Interest Rate',
	MIN_BALANCE: 'Min Balance',
};
